variables:
 # public
 - ${{ if eq(variables['System.TeamProject'], 'public') }}:
   - name: connectionString
     value: ''
 # internal
 - ${{ if ne(variables['System.TeamProject'], 'public') }}:
   - group: AzureSDK KeyVault - AzConfig LiveTest
   - name: connectionString
     value: $(AzConfigConnection)

jobs:
- job: 'Test'

  strategy:
    matrix:
      Linux:
        os.vmImage: 'ubuntu-16.04'
      macOS:
        os.vmImage: 'macOS-10.13'
      Windows:
        os.vmImage: 'vs2017-win2016'

  pool:
    vmImage: '$(os.vmImage)'

  steps:
    - task: DotNetCoreCLI@2
      displayName: 'Test Mocks'
      condition: eq(variables['System.TeamProject'], 'public')
      inputs:
        projects: '**/*.Test/*.csproj'
        command: test
        arguments: --filter TestCategory!=Live
  
    - task: DotNetCoreCLI@2
      displayName: 'Test'
      condition: ne(variables['System.TeamProject'], 'public')
      env:
        AZ_CONFIG_CONNECTION: $(connectionString)
      inputs:
        projects: '**/*.Test/*.csproj'
        command: test

- job: 'Publish'

  dependsOn:
    - 'Test'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: dotnet pack --output $(Build.ArtifactStagingDirectory)
    displayName: 'Pack'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
